use sisa;

delete from pages_roles;
delete from bibliographies_authors;
delete from academics_periods_courses;
delete from disciplines_bibliographies;
delete from procedures_evaluations;
delete from campus_courses;
delete from verifications;
delete from responsibles;
delete from users_roles;
delete from authors;
delete from bibliographies;
delete from campus;
delete from menus where parent_id is not null;
delete from menus;
delete from pages;
delete from actions;
delete from classes_programming;
delete from teaching_plans;
delete from ppcs_disciplines;
delete from ppcs;
delete from courses;
delete from disciplines;
delete from evaluations;
delete from rectories;
delete from roles;
delete from traineeships;
delete from users;
delete from academics_periods;